return {
    ["BUILD.bazel"] = { "starlark_rust" },
    OpenFOAM = { "foam_ls" },
    PKGBUILD = { "termux_language_server" },
    ada = { "ada_ls" },
    agda = { "agda_ls" },
    aiken = { "aiken" },
    alloy = { "alloy_ls" },
    antlers = { "antlersls" },
    arduino = { "arduino_language_server" },
    asm = { "asm_lsp" },
    asm68k = { "m68k" },
    aspnetcorerazor = { "htmx", "tailwindcss" },
    astro = {
        "astro",
        "biome",
        "emmet_language_server",
        "emmet_ls",
        "eslint",
        "htmx",
        "stylelint_lsp",
        "tailwindcss",
        "unocss",
    },
    ["astro-markdown"] = { "htmx", "tailwindcss" },
    ["atlas-*"] = { "atlas" },
    ato = { "atopile" },
    autohotkey = { "autohotkey_lsp" },
    automake = { "autotools_ls" },
    autopkgtest = { "debputy" },
    awk = { "awk_ls" },
    ballerina = { "ballerina" },
    bash = { "bashls" },
    bazelrc = { "bazelrc_lsp" },
    bean = { "beancount" },
    beancount = { "beancount" },
    bib = { "ltex", "ltex_plus", "texlab" },
    bicep = { "bicep" },
    ["bicep-params"] = { "bicep" },
    bitbake = { "bitbake_language_server" },
    blade = { "htmx", "laravel_ls", "stimulus_ls", "tailwindcss", "turbo_ls" },
    blueprint = { "blueprint_ls" },
    brs = { "bright_script" },
    bsl = { "bsl_ls" },
    bzl = { "buck2", "bzl", "please", "starlark_rust", "starpls" },
    c = { "ast_grep", "ccls", "clangd", "codebook", "harper_ls", "sourcekit" },
    c3 = { "c3_lsp" },
    c3i = { "c3_lsp" },
    cairo = { "cairo_ls" },
    cds = { "cds_lsp" },
    cir = { "cir_lsp_server" },
    circom = { "circom-lsp" },
    clar = { "clarinet" },
    clarity = { "clarinet" },
    clojure = { "clojure_lsp", "harper_ls", "htmx", "tailwindcss" },
    cmake = { "cmake", "harper_ls", "neocmake" },
    cnf = { "dolmenls" },
    cobol = { "cobol_ls" },
    coffee = { "coffeesense" },
    comp = { "glsl_analyzer", "glslls" },
    config = { "autotools_ls" },
    context = { "digestif", "ltex", "ltex_plus" },
    coq = { "coq_lsp", "vscoqtop" },
    cpp = { "ast_grep", "ccls", "clangd", "harper_ls", "sourcekit", "tvm_ffi_navigator" },
    crystal = { "crystalline", "scry" },
    cs = { "csharp_ls", "harper_ls", "omnisharp", "roslyn_ls" },
    css = {
        "ast_grep",
        "biome",
        "codebook",
        "css_variables",
        "cssls",
        "emmet_language_server",
        "emmet_ls",
        "stylelint_lsp",
        "tailwindcss",
        "unocss",
    },
    cucumber = { "cucumber_language_server" },
    cuda = { "ccls", "clangd" },
    cue = { "cue", "dagger" },
    cypher = { "cypher_ls" },
    d = { "daedalus_ls", "serve_d" },
    dafny = { "dafny" },
    dart = { "ast_grep", "dartls", "dcmls", "harper_ls" },
    debchangelog = { "debputy" },
    debcontrol = { "debputy" },
    debcopyright = { "debputy" },
    dfy = { "dafny" },
    dhall = { "dhall_lsp_server" },
    ["django-html"] = { "htmx", "tailwindcss" },
    dockerfile = { "docker_language_server", "dockerls" },
    dot = { "dotls" },
    dts = { "dts_lsp", "ginko_ls" },
    dtsi = { "dts_lsp" },
    dune = { "ocamllsp" },
    earthfile = { "earthlyls" },
    ecsact = { "ecsact" },
    edge = { "htmx", "tailwindcss" },
    edn = { "clojure_lsp" },
    eelixir = { "elixirls", "expert", "htmx", "lexical", "nextls", "tailwindcss" },
    ejs = { "htmx", "tailwindcss", "unocss" },
    elixir = { "elixirls", "expert", "htmx", "lexical", "nextls", "tailwindcss" },
    elm = { "elmls" },
    erb = { "htmx", "tailwindcss", "unocss" },
    erg = { "erg_language_server" },
    erlang = { "elp", "erlangls" },
    eruby = {
        "emmet_language_server",
        "emmet_ls",
        "herb_ls",
        "htmx",
        "ruby_lsp",
        "steep",
        "stimulus_ls",
        "tailwindcss",
        "turbo_ls",
        "typeprof",
    },
    fennel = { "fennel_language_server", "fennel_ls" },
    fish = { "fish_lsp" },
    flux = { "flux_lsp" },
    foam = { "foam_ls" },
    fortran = { "fortls" },
    frag = { "glsl_analyzer", "glslls" },
    fsd = { "facility_language_server" },
    fsharp = { "fsautocomplete", "fsharp_language_server" },
    fstar = { "fstar" },
    fut = { "futhark_lsp" },
    futhark = { "futhark_lsp" },
    gd = { "gdscript" },
    gdscript = { "gdscript" },
    gdscript3 = { "gdscript" },
    gdshader = { "gdshader_lsp" },
    gdshaderinc = { "gdshader_lsp" },
    genie = { "vala_ls" },
    geom = { "glsl_analyzer", "glslls" },
    gitcommit = { "codebook", "harper_ls", "ltex", "ltex_plus" },
    gleam = { "gleam" },
    glsl = { "glsl_analyzer", "glslls" },
    gn = { "gnls" },
    go = { "ast_grep", "codebook", "golangci_lint_ls", "gopls", "harper_ls", "snyk_ls" },
    gohtml = { "htmx", "tailwindcss" },
    gohtmltmpl = { "htmx", "tailwindcss" },
    gomod = { "golangci_lint_ls", "gopls", "snyk_ls" },
    gotmpl = { "gopls" },
    gowork = { "gopls" },
    graphql = { "biome", "dprint", "graphql" },
    groovy = { "gradle_ls", "groovyls" },
    hack = { "hhvm" },
    haml = { "htmx", "tailwindcss", "unocss" },
    handlebars = { "ember", "glint", "htmx", "tailwindcss" },
    haskell = { "codebook", "ghcide", "harper_ls", "hie", "hls", "ttags" },
    hbs = { "htmx", "tailwindcss", "unocss" },
    hcl = { "terraform_lsp" },
    ["hcl.nomad"] = { "nomad_lsp" },
    heex = { "elixirls", "expert", "htmx", "lexical", "nextls", "tailwindcss" },
    helm = { "helm_ls", "snyk_ls" },
    hlasm = { "hlasm" },
    hlsl = { "slangd" },
    hoon = { "hoon_ls" },
    html = {
        "angularls",
        "antlersls",
        "ast_grep",
        "biome",
        "codebook",
        "djlsp",
        "emmet_language_server",
        "emmet_ls",
        "harper_ls",
        "herb_ls",
        "html",
        "htmx",
        "ltex",
        "ltex_plus",
        "lwc_ls",
        "stimulus_ls",
        "stylelint_lsp",
        "superhtml",
        "tailwindcss",
        "turbo_ls",
        "unocss",
    },
    ["html-eex"] = { "htmx", "tailwindcss" },
    ["html.handlebars"] = { "glint" },
    htmlangular = { "angularls", "emmet_language_server", "emmet_ls", "eslint", "htmx", "tailwindcss" },
    htmldjango = { "djlsp", "emmet_language_server", "emmet_ls", "htmx", "tailwindcss" },
    http = { "kulala_ls" },
    hyprlang = { "hyprls" },
    icnf = { "dolmenls" },
    idris2 = { "idris2_lsp" },
    jade = { "htmx", "tailwindcss" },
    janet = { "janet_lsp" },
    java = { "ast_grep", "codebook", "harper_ls", "java_language_server", "jdtls" },
    javascript = {
        "ast_grep",
        "biome",
        "codebook",
        "cssmodules_ls",
        "denols",
        "dprint",
        "ember",
        "eslint",
        "flow",
        "glint",
        "harper_ls",
        "htmx",
        "lwc_ls",
        "oxlint",
        "quick_lint_js",
        "rome",
        "snyk_ls",
        "tailwindcss",
        "ts_ls",
        "tsgo",
        "ttags",
        "unocss",
        "vtsls",
    },
    ["javascript.glimmer"] = { "ember", "glint" },
    ["javascript.jsx"] = { "ast_grep", "denols", "eslint", "flow", "oxlint", "ts_ls", "tsgo", "vtsls" },
    javascriptreact = {
        "ast_grep",
        "biome",
        "codebook",
        "cssmodules_ls",
        "denols",
        "dprint",
        "emmet_language_server",
        "emmet_ls",
        "eslint",
        "flow",
        "graphql",
        "htmx",
        "oxlint",
        "rome",
        "tailwindcss",
        "ts_ls",
        "tsgo",
        "unocss",
        "vtsls",
    },
    jinja = { "jinja_lsp" },
    jq = { "jqls" },
    json = { "biome", "dprint", "jsonls", "nxls", "rome", "snyk_ls", "spectral" },
    ["json.openapi"] = { "vacuum" },
    jsonc = { "biome", "dprint", "jsonls", "nxls" },
    jsonnet = { "jsonnet_ls" },
    julia = { "julials" },
    just = { "just" },
    kcl = { "kcl" },
    koka = { "koka" },
    kotlin = { "ast_grep", "kotlin_language_server", "kotlin_lsp" },
    leaf = { "htmx", "tailwindcss" },
    lean3 = { "lean3ls" },
    less = { "css_variables", "cssls", "emmet_language_server", "emmet_ls", "stylelint_lsp", "tailwindcss", "unocss" },
    lhaskell = { "ghcide", "hls" },
    libsonnet = { "jsonnet_ls" },
    liquid = { "htmx", "shopify_theme_ls", "tailwindcss", "theme_check" },
    llw = { "lelwel_ls" },
    lua = { "ast_grep", "codebook", "emmylua_ls", "harper_ls", "lua_ls", "selene3p_ls", "stylua3p_ls" },
    luau = { "luau_lsp" },
    mail = { "ltex", "ltex_plus" },
    make = { "autotools_ls", "debputy" },
    markdown = {
        "codebook",
        "dprint",
        "ds_pinyin_lsp",
        "grammarly",
        "harper_ls",
        "htmx",
        "ltex",
        "ltex_plus",
        "markdown_oxide",
        "marksman",
        "prosemd_lsp",
        "remark_ls",
        "tailwindcss",
        "unocss",
        "vale_ls",
        "zk",
    },
    ["markdown.mdx"] = { "marksman" },
    marko = { "marko-js" },
    matlab = { "matlab_ls" },
    mcfunction = { "spyglassmc_language_server" },
    mdx = { "htmx", "ltex_plus", "mdx_analyzer", "tailwindcss" },
    menhir = { "ocamllsp" },
    meson = { "mesonlsp", "muon", "swift_mesonls" },
    ["metamath-zero"] = { "mm0_ls" },
    mint = { "mint" },
    mlir = { "buddy_ls", "mlir_lsp_server" },
    mojo = { "mojo" },
    motoko = { "motoko_lsp" },
    move = { "move_analyzer" },
    msbuild = { "msbuild_project_tools_server" },
    mustache = { "htmx", "tailwindcss" },
    muttrc = { "mutt_ls" },
    mysql = { "sqlls", "sqls" },
    ncl = { "nickel_ls" },
    nelua = { "nelua_lsp" },
    neomuttrc = { "mutt_ls" },
    nextflow = { "nextflow_ls" },
    nginx = { "nginx_language_server" },
    nickel = { "nickel_ls" },
    nim = { "nim_langserver", "nimls" },
    nix = { "harper_ls", "nil_ls", "nixd", "rnix", "statix" },
    njk = { "htmx", "tailwindcss" },
    nomad = { "nomad_lsp" },
    nu = { "nushell" },
    nunjucks = { "htmx", "tailwindcss" },
    objc = { "ccls", "clangd", "sourcekit" },
    objcpp = { "ccls", "clangd", "sourcekit" },
    ocaml = { "ocamlls", "ocamllsp" },
    ocamlinterface = { "ocamllsp" },
    ocamllex = { "ocamllsp" },
    odin = { "ols" },
    opencl = { "opencl_ls" },
    openscad = { "openscad_ls", "openscad_lsp" },
    opentofu = { "tofu_ls" },
    ["opentofu-vars"] = { "tofu_ls" },
    org = { "ds_pinyin_lsp", "ltex", "ltex_plus", "textlsp" },
    os = { "bsl_ls" },
    overlay = { "dts_lsp" },
    p = { "dolmenls" },
    p8 = { "pico8_ls" },
    pact = { "pact_ls" },
    pandoc = { "ltex", "ltex_plus" },
    pascal = { "pasls" },
    pdll = { "mlir_pdll_lsp_server" },
    perl = { "perlls", "perlnavigator", "perlpls" },
    pest = { "pest_ls" },
    php = {
        "codebook",
        "harper_ls",
        "hhvm",
        "htmx",
        "intelephense",
        "laravel_ls",
        "phan",
        "phpactor",
        "phptools",
        "psalm",
        "stimulus_ls",
        "tailwindcss",
        "turbo_ls",
        "unocss",
    },
    plaintex = { "digestif", "ltex", "ltex_plus", "texlab" },
    pli = { "pli" },
    pory = { "poryscript_pls" },
    postcss = { "tailwindcss", "unocss" },
    prisma = { "prismals" },
    profile = { "vespa_ls" },
    prolog = { "prolog_ls" },
    proto = { "buf_ls", "bufls", "pbls", "protols" },
    ps1 = { "powershell_es" },
    pug = { "emmet_language_server", "emmet_ls", "pug" },
    puppet = { "puppet" },
    purescript = { "purescriptls" },
    python = {
        "anakin_language_server",
        "ast_grep",
        "basedpyright",
        "codebook",
        "dprint",
        "harper_ls",
        "jedi_language_server",
        "pylsp",
        "pylyzer",
        "pyre",
        "pyrefly",
        "pyright",
        "ruff",
        "ruff_lsp",
        "snyk_ls",
        "tvm_ffi_navigator",
        "ty",
        "zuban",
    },
    qml = { "qmlls" },
    qmljs = { "qmlls" },
    quarto = { "ltex", "ltex_plus", "r_language_server" },
    query = { "ts_query_ls" },
    r = { "air", "r_language_server" },
    racket = { "racket_langserver" },
    raku = { "raku_navigator" },
    razor = { "htmx", "tailwindcss" },
    reason = { "htmx", "ocamlls", "ocamllsp", "reason_ls", "tailwindcss" },
    rego = { "regal", "regols" },
    requirements = { "snyk_ls" },
    rescript = { "htmx", "rescriptls", "tailwindcss", "unocss" },
    resource = { "robotcode" },
    rmd = { "ltex", "ltex_plus", "r_language_server" },
    rnoweb = { "ltex", "ltex_plus" },
    robot = { "robotcode", "robotframework_ls" },
    roc = { "roc_ls" },
    roslyn = { "dprint" },
    rst = { "esbonio", "ltex", "ltex_plus", "vale_ls" },
    ruby = {
        "codebook",
        "harper_ls",
        "rubocop",
        "ruby_lsp",
        "solargraph",
        "sorbet",
        "standardrb",
        "steep",
        "stimulus_ls",
        "syntax_tree",
        "ttags",
        "turbo_ls",
        "typeprof",
    },
    rune = { "rune_languageserver" },
    rust = { "ast_grep", "bacon_ls", "codebook", "dprint", "harper_ls", "rls", "rust_analyzer", "ttags", "unocss" },
    sass = { "emmet_language_server", "emmet_ls", "somesass_ls", "tailwindcss", "unocss" },
    scala = { "metals" },
    scheme = { "racket_langserver", "scheme_langserver" },
    ["scheme.guile"] = { "guile_ls" },
    scss = {
        "css_variables",
        "cssls",
        "emmet_language_server",
        "emmet_ls",
        "somesass_ls",
        "stylelint_lsp",
        "tailwindcss",
        "unocss",
    },
    sd = { "vespa_ls" },
    sh = { "bashls" },
    shaderslang = { "slangd" },
    sixtyfps = { "sixtyfps" },
    slim = { "htmx", "tailwindcss" },
    slint = { "slint_lsp" },
    sls = { "salt_ls" },
    smarty = { "smarty_ls" },
    smithy = { "smithy_ls" },
    sml = { "millet" },
    smt2 = { "dolmenls" },
    solidity = { "solang", "solc", "solidity", "solidity_ls", "solidity_ls_nomicfoundation" },
    spec = { "rpmspec" },
    sql = { "bqls", "postgres_lsp", "sqlls", "sqls", "sqruff" },
    ss = { "snakeskin_ls" },
    star = { "starlark_rust" },
    stylus = { "tailwindcss", "unocss" },
    sugarss = { "stylelint_lsp", "tailwindcss" },
    superhtml = { "superhtml" },
    surface = { "elixirls", "expert", "lexical", "nextls" },
    svelte = { "biome", "emmet_language_server", "emmet_ls", "eslint", "htmx", "svelte", "tailwindcss", "unocss" },
    svg = { "lemminx" },
    swift = { "harper_ls", "sourcekit" },
    systemd = { "systemd_ls" },
    systemverilog = { "hdl_checker", "svlangserver", "svls", "verible", "veridian" },
    tablegen = { "tblgen_lsp_server" },
    teal = { "teal_ls" },
    templ = { "emmet_language_server", "emmet_ls", "html", "htmx", "tailwindcss", "templ" },
    terraform = { "snyk_ls", "terraform_lsp", "terraformls", "tflint" },
    ["terraform-vars"] = { "snyk_ls", "terraformls" },
    tesc = { "glsl_analyzer", "glslls" },
    tese = { "glsl_analyzer", "glslls" },
    tex = { "digestif", "ltex", "ltex_plus", "texlab", "textlsp", "vale_ls" },
    text = { "codebook", "ltex", "ltex_plus", "textlsp", "vale_ls" },
    thrift = { "thriftls" },
    tiltfile = { "tilt_ls" },
    toml = { "codebook", "dprint", "harper_ls", "taplo", "tombi" },
    tptp = { "dolmenls" },
    ttcn = { "ntt" },
    ttl = { "turtle_ls" },
    turtle = { "turtle_ls" },
    twig = { "htmx", "tailwindcss", "twiggy_language_server" },
    typescript = {
        "angularls",
        "ast_grep",
        "biome",
        "codebook",
        "cssmodules_ls",
        "denols",
        "dprint",
        "ember",
        "eslint",
        "glint",
        "harper_ls",
        "htmx",
        "oxlint",
        "quick_lint_js",
        "rome",
        "snyk_ls",
        "tailwindcss",
        "ts_ls",
        "tsgo",
        "unocss",
        "vtsls",
    },
    ["typescript.glimmer"] = { "ember", "glint" },
    ["typescript.tsx"] = {
        "angularls",
        "ast_grep",
        "biome",
        "denols",
        "eslint",
        "oxlint",
        "rome",
        "ts_ls",
        "tsgo",
        "vtsls",
    },
    typescriptreact = {
        "angularls",
        "ast_grep",
        "biome",
        "codebook",
        "cssmodules_ls",
        "denols",
        "dprint",
        "emmet_language_server",
        "emmet_ls",
        "eslint",
        "graphql",
        "harper_ls",
        "htmx",
        "oxlint",
        "rome",
        "tailwindcss",
        "ts_ls",
        "tsgo",
        "unocss",
        "vtsls",
    },
    typespec = { "tsp_server" },
    typst = { "harper_ls", "ltex_plus", "tinymist", "typst_lsp" },
    uiua = { "uiua" },
    ungrammar = { "ungrammar_languageserver" },
    unison = { "unison" },
    uvl = { "uvls" },
    v = { "v_analyzer", "vls" },
    vala = { "vala_ls" },
    vb = { "omnisharp" },
    verilog = { "hdl_checker", "svlangserver", "svls", "verible", "veridian" },
    vert = { "glsl_analyzer", "glslls" },
    veryl = { "veryl_ls" },
    vhd = { "vhdl_ls" },
    vhdl = { "ghdl_ls", "hdl_checker", "vhdl_ls" },
    vim = { "vimls" },
    visualforce = { "visualforce_ls" },
    vlang = { "vls" },
    vmasm = { "asm_lsp" },
    vsh = { "v_analyzer" },
    vue = {
        "biome",
        "emmet_language_server",
        "emmet_ls",
        "eslint",
        "htmx",
        "stylelint_lsp",
        "tailwindcss",
        "unocss",
        "vue_ls",
    },
    ["vue-html"] = { "unocss" },
    vv = { "v_analyzer" },
    wat = { "wasm_language_tools" },
    wgsl = { "glasgow", "wgsl_analyzer" },
    wxss = { "stylelint_lsp" },
    xhtml = { "ltex", "ltex_plus" },
    xml = { "lemminx" },
    xsd = { "lemminx" },
    xsl = { "lemminx" },
    xslt = { "lemminx" },
    yaml = { "azure_pipelines_ls", "debputy", "gh_actions_ls", "hydra_lsp", "snyk_ls", "spectral", "yamlls" },
    ["yaml.ansible"] = { "ansiblels" },
    ["yaml.docker-compose"] = { "docker_compose_language_service", "docker_language_server", "yamlls" },
    ["yaml.gitlab"] = { "gitlab_ci_ls", "yamlls" },
    ["yaml.helm-values"] = { "helm_ls", "yamlls" },
    ["yaml.openapi"] = { "vacuum" },
    yang = { "yang_lsp" },
    yar = { "yls" },
    yara = { "yls" },
    yml = { "spectral" },
    yql = { "vespa_ls" },
    zf = { "dolmenls" },
    zig = { "zls" },
    ziggy = { "ziggy" },
    ziggy_schema = { "ziggy_schema" },
    zir = { "zls" },
}
