- name: "Install"
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: "Calculate paths"
  ansible.builtin.set_fact:
    conf_path: "{{ (xdg_config_home, 'zsh') | path_join }}"

- name: "Create config path"
  ansible.builtin.file:
    path: "{{ conf_path }}"
    state: directory
    mode: '0755'

- name: "Link files"
  loop:
    - {src: "zshenv", dest: "{{ (ansible_env.HOME, '.zshenv') | path_join }}"}
    - {src: "zshrc", dest: "{{ (conf_path, '.zshrc') | path_join }}"}
    - {src: "meow.txt", dest: "{{ (conf_path, 'meow.txt') | path_join }}"}
  ansible.builtin.file:
    src: "{{ (role_path, 'files', item.src) | path_join }}"
    dest: "{{ item.dest }}"
    state: link

- name: "Install z.lua"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/skywind3000/z.lua/1.8.20/z.lua
    dest: "{{ (ansible_env.HOME, '.local', 'bin', 'z.lua') | path_join }}"
    mode: '0755'
    checksum: sha256:099a4443a74f5378a6bb644986836597abe956841ce63d14634bce611bba657c

- name: "Install fzf-tab"
  ansible.builtin.git:
    repo: https://github.com/Aloxaf/fzf-tab
    version: v1.1.2
    dest: "{{ (conf_path, 'plugins', 'fzf-tab') | path_join }}"
