- name: "Install"
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: "Calculate paths"
  ansible.builtin.set_fact:
    conf_path: "{{ (xdg_config_home, 'zsh') | path_join }}"

- name: "Create config path"
  ansible.builtin.file:
    path: "{{ conf_path }}"
    state: directory
    mode: '0755'

- name: "Link files"
  loop:
    - {src: "zshenv", dest: "{{ (ansible_env.HOME, '.zshenv') | path_join }}"}
    - {src: "zshrc", dest: "{{ (conf_path, '.zshrc') | path_join }}"}
    - {src: "meow.txt", dest: "{{ (conf_path, 'meow.txt') | path_join }}"}
  ansible.builtin.file:
    src: "{{ (role_path, 'files', item.src) | path_join }}"
    dest: "{{ item.dest }}"
    state: link
