- name: Install
  become: true
  ansible.builtin.package:
    name: kitty
    state: present

- name: Sync kitty-themes
  ansible.builtin.git:
    repo: https://github.com/dexpota/kitty-themes.git
    dest: "{{ (xdg_data_home, 'kitty-themes') | path_join }}"
    version: master
    depth: 1
    accept_newhostkey: true

- name: Update bundled themes
  loop:
    - LICENSE.md
    - README.md
    - themes/
  ansible.posix.synchronize:
    src: "{{ (xdg_data_home, 'kitty-themes', item) | path_join }}"
    dest: "{{ (role_path, 'files', 'themes/') | path_join }}"

- name: Link configuration
  ansible.builtin.file:
    src: "{{ (role_path, 'files') | path_join }}"
    dest: "{{ (xdg_config_home, 'kitty') | path_join }}"
    state: link
