anchor=top
#dpi-aware=no
icon-theme=Papirus-Dark
width=40
font=Hack:weight=normal:size=16
fields=name,generic,comment,categories,filename,keywords
terminal=kitty -o shell=
prompt="❯   "
show-actions=yes
exit-on-keyboard-focus-loss=no

[colors]
background=282a36fa
selection=3d4474fa
border=fffffffa

[border]
radius=15

[dmenu]
exit-immediately-if-empty=yes

