- name: "Calculate paths"
  ansible.builtin.set_fact:
    conf_path: "{{ (xdg_config_home, 'docker') | path_join }}"

- name: "Create config path"
  ansible.builtin.file:
    path: "{{ conf_path }}"
    state: directory
    mode: '0755'

# Copy instead of link because this file ends up containing credentials
- name: "Copy config.json"
  ansible.builtin.copy:
    src: "{{ (role_path, 'files', 'config.json') | path_join }}"
    dest: "{{ (conf_path, 'config.json') | path_join }}"
    mode: '0600'
