- name: "Install packages"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - lazygit
      - stylua
      - shellcheck
      - basedpyright-bin
      - lua-language-server
      - vscode-json-languageserver
      - vscode-css-languageserver
      - vscode-html-languageserver 

- name: "Include roles"
  loop:
    - neovim
    - vscode
    - git
    - mercurial
    - asdf
    - direnv
  loop_control:
    loop_var: dev_role
  ansible.builtin.include_role:
    name: "{{ dev_role }}"
  tags: [dev]
