- name: "Install"
  become: true
  ansible.builtin.package:
    name:
      - xmonad
      - xmonad-contrib
      - xmobar
    state: present

- name: "Calculate paths"
  ansible.builtin.set_fact:
    xmonad_conf_path: "{{ (xdg_config_home, 'xmonad') | path_join }}"
    xmobar_conf_path: "{{ (xdg_config_home, 'xmobar') | path_join }}"

- name: "Create paths"
  loop:
    - "{{ xmonad_conf_path }}"
    - "{{ xmobar_conf_path }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'

- name: Link xmonad.hs
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'xmonad.hs') | path_join }}"
    dest: "{{ (xmonad_conf_path, 'xmonad.hs') | path_join }}"
    state: link

- name: Link xmobarrc
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'xmobarrc') | path_join }}"
    dest: "{{ (xmobar_conf_path, 'xmobarrc') | path_join }}"
    state: link
