- name: "Install"
  become: true
  ansible.builtin.package:
    name: neovim
    state: present

- name: "Calculate paths"
  ansible.builtin.set_fact:
    conf_path: "{{ (xdg_config_home, 'nvim') | path_join }}"

- name: "Create config path"
  ansible.builtin.file:
    path: "{{ conf_path }}"
    state: directory
    mode: '0755'

- name: "Locate files"
  register: files
  ansible.builtin.find:
    paths: "{{ (role_path, 'files') | path_join }}"
    file_type: any
    get_checksum: true

- name: "Link files"
  loop: "{{ files.files }}"
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ (conf_path, (item.path | basename)) | path_join }}"
    state: link

#- name: "Install vim-plug"
#  ansible.builtin.get_url:
#    url: https://raw.githubusercontent.com/junegunn/vim-plug/0.14.0/plug.vim
#    dest: "{{ (xdg_data_home, 'nvim', 'site', 'autoload', 'plug.vim') | path_join }}"
#    mode: '0644'
#    checksum: sha256:20b4c895f98d13848204698068c4dd031730d4e7c9c4b630d6273b9b9afcdcdb

- name: "Setup Python virtualenv"
  ansible.builtin.pip:
    virtualenv_command: "python3 -m venv"
    virtualenv: "{{ (ansible_env.HOME, '.envs', 'nvim') | path_join }}"
    extra_args: --upgrade
    name:
      - pip
      - pynvim
      - jedi

# NO LONGER NEEDED WITH MOVE TO LUA/LAZYVIM
# - name: "Update checksums"
#   notify: UpdateNeovimPlugins
#   ansible.builtin.copy:
#     dest: "{{ (conf_path, 'anisble.sha1') | path_join }}"
#     content: "{% for file in files.files %}{{ file.checksum }}  {{ file.path | basename }}\n{% endfor %}"
#     mode: '0644'
