- name: "Install"
  become: true
  ansible.builtin.package:
    name: neovim
    state: present

- name: Link configuration
  ansible.builtin.file:
    src: "{{ (role_path, 'files') | path_join }}"
    dest: "{{ (xdg_config_home, 'nvim') | path_join }}"
    state: link

- name: "Setup Python virtualenv"
  ansible.builtin.pip:
    virtualenv_command: "python3 -m venv"
    virtualenv: "{{ (ansible_env.HOME, '.envs', 'nvim') | path_join }}"
    extra_args: --upgrade
    name:
      - pip
      - pynvim
      - jedi

- name: ":Lazy sync"
  command: nvim --headless "+Lazy! sync" +qa

# NO LONGER NEEDED WITH MOVE TO LUA/LAZYVIM
# - name: "Update checksums"
#   notify: UpdateNeovimPlugins
#   ansible.builtin.copy:
#     dest: "{{ (conf_path, 'anisble.sha1') | path_join }}"
#     content: "{% for file in files.files %}{{ file.checksum }}  {{ file.path | basename }}\n{% endfor %}"
#     mode: '0644'
